# Запрашиваем все записи
GET {{host-url}}/list/all
###

# Запрашиваем обязательные комплектующие
GET {{host-url}}/list/required
###

# Запрашиваем необязательные комплектующие
GET {{host-url}}/list/optional
###

# Запрашиваем комплектующее
GET {{host-url}}/part/2
###

# Запрашиваем удаление комплектующего с id = 2
DELETE {{host-url}}/part/delete/2
###




